import { useState, useEffect, useCallback } from 'react';
import { Drawing, ThemeColors } from '../types';
import { ApiClient } from '../api/ApiClient';

/**
 * Custom hook for managing drawing storage operations
 * @param clearCanvas Function to clear the canvas
 * @param canvasRef Reference to the canvas element
 * @param canvasSize Canvas size dimensions
 * @param activeThemeColors Current theme colors
 */
export const useDrawingStorage = (
  clearCanvas: () => void, 
  canvasRef: React.RefObject<HTMLCanvasElement>,
  canvasSize: { width: number, height: number },
  activeThemeColors: ThemeColors
) => {  const [drawings, setDrawings] = useState<Drawing[]>([]);
  const [currentDrawingName, setCurrentDrawingName] = useState<string>('My Drawing');
  const apiClient = ApiClient.getInstance();
  // Load drawings from db
  useEffect(() => {
    const fetchDrawings = async () => {
      try {
        const savedDrawings = await apiClient.getDrawings();
        if(!savedDrawings || savedDrawings.length === 0)
          return;
  
        setDrawings(savedDrawings);
      } catch (error) {
        console.error('Error fetching drawings:', error);
      }
    };
    fetchDrawings();

  }, [apiClient]);

  // Helper function to prepare a new drawing
  const prepareNewDrawing = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const tempCanvas = document.createElement('canvas');
    tempCanvas.width = canvasSize.width;
    tempCanvas.height = canvasSize.height;
    const tempCtx = tempCanvas.getContext('2d');

    if (!tempCtx) return;

    tempCtx.fillStyle = activeThemeColors.background;
    tempCtx.fillRect(0, 0, tempCanvas.width, tempCanvas.height);
    tempCtx.drawImage(canvas, 0, 0, canvas.width, canvas.height, 0, 0, tempCanvas.width, tempCanvas.height);

    const dataUrl = tempCanvas.toDataURL('image/png');
    const newDrawing: Drawing = {
      // No id property for new drawings, since it will be generated by the server
      name: currentDrawingName || 'Untitled Drawing',
      dataUrl,
      timestamp: Date.now(),
    };    

    return newDrawing;
  }, [activeThemeColors.background, canvasRef, canvasSize, currentDrawingName]);

  // Save drawing
  const saveDrawing = useCallback(() => {
    const newDrawing = prepareNewDrawing();
    if (!newDrawing) return;
    
   apiClient.saveDrawing(newDrawing)
        .then((savedDrawing) => {
          setDrawings(prev => [...prev, savedDrawing]);
          alert('Drawing saved!');
        })
        .catch(error => {
          console.error('Error saving drawing to database:', error);
          alert('Error saving drawing. Please try again.');
        });
  }, [prepareNewDrawing, apiClient]);

  // Update existing drawing
  const updateDrawing = useCallback((drawingId: string) => {

    const existingDrawing = drawings.find(d => d.id === drawingId);
    if (!existingDrawing) return;
    
    // Create new drawing but preserve the original ID
    const newDrawing = prepareNewDrawing();
    if (!newDrawing) return;
    
    newDrawing.id = drawingId;

    apiClient.updateDrawing(drawingId, newDrawing)
        .then(updatedDrawing => {
          setDrawings(prevDrawings => {
            const updatedDrawings = prevDrawings.map(d => d.id === drawingId ? updatedDrawing : d);
            return updatedDrawings;
          });
          alert('Drawing updated!');
        })
        .catch(error => {
          console.error('Error updating drawing in database:', error);
          alert('Error updating drawing. Please try again.');
        });
  }, [drawings, prepareNewDrawing, apiClient]);

  // Load drawings
  const loadDrawing = useCallback((drawingId: string, drawingDataUrl: string) => {
    // Find the drawing by ID and get its name
    const drawing = drawings.find(d => d.id === drawingId);
    if (drawing) {
      setCurrentDrawingName(drawing.name);
    } else {
      setCurrentDrawingName('New Drawing');
    }

    // Clear the canvas before loading a new drawing
    clearCanvas();

    const canvas = canvasRef.current;
    if (!canvas) return;
    
    const context = canvas.getContext('2d');
    if (!context) return;

    const img = new Image();
    img.onload = () => {
      context.drawImage(img, 0, 0, canvasSize.width, canvasSize.height);
      context.strokeStyle = activeThemeColors.stroke;    };
    img.onerror = () => {
      console.error('Error loading image from data URL');
      alert('Error loading drawing. The image data may be corrupted.');
    };
    img.src = drawingDataUrl;
  }, [activeThemeColors.stroke, canvasRef, canvasSize, clearCanvas, drawings]);

  // Delete drawing
  const deleteDrawing = useCallback((drawingId: string) => {
    if(!window.confirm('Are you sure you want to delete this drawing?')) return;

    apiClient.deleteDrawing(drawingId)
      .then(() => {
        setDrawings(prevDrawings => {
          const updatedDrawings = prevDrawings.filter(d => d.id !== drawingId);
          return updatedDrawings;
        });
      })
      .catch(error => {
        console.error('Error deleting drawing from database:', error);
        alert('Error deleting drawing. Please try again.');
      });
  }, [apiClient]);

  // Export to PDF
  const exportToPdf = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    // Dynamically import jsPDF to avoid issues with SSR
    import('jspdf').then(({ default: jsPDF }) => {
      const tempExportCanvas = document.createElement('canvas');
      tempExportCanvas.width = canvasSize.width;
      tempExportCanvas.height = canvasSize.height;
      const tempExportCtx = tempExportCanvas.getContext('2d');
  
      if (!tempExportCtx) {
        alert('Could not prepare canvas for PDF export.');
        return;
      }
  
      tempExportCtx.fillStyle = activeThemeColors.background;
      tempExportCtx.fillRect(0, 0, tempExportCanvas.width, tempExportCanvas.height);
      tempExportCtx.drawImage(canvas, 0, 0, canvas.width, canvas.height, 0, 0, tempExportCanvas.width, tempExportCanvas.height);
  
      const imgData = tempExportCanvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: tempExportCanvas.width > tempExportCanvas.height ? 'landscape' : 'portrait',
        unit: 'px',
        format: [tempExportCanvas.width, tempExportCanvas.height]
      });
      
      pdf.addImage(imgData, 'PNG', 0, 0, tempExportCanvas.width, tempExportCanvas.height);
      pdf.save(`${currentDrawingName.replace(/\s+/g, '_') || 'drawing'}.pdf`);
    });
  }, [activeThemeColors.background, canvasRef, canvasSize, currentDrawingName]);

  return {
    drawings,
    currentDrawingName,
    setCurrentDrawingName,
    saveDrawing,
    updateDrawing,
    loadDrawing,
    deleteDrawing,
    exportToPdf
  };
};
